#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

# first, run composer req annotations
backend_controllers:
    resource: ../src/Controller/Backend
    type: annotation
